name: neurafs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
      - fastapi
      - uvicorn
      - pydantic
      - python-multipart
      - numpy
      - scipy
      - psutil
      - torch
      - torchaudio
      - torchvision
